const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
  SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
  CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',
  //user
  ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
  PROCESS_LOGOUT: 'PROCESS_LOGOUT',

  //admin
  // allcode-derived types removed (gender/position/role)

  CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
  CREATE_USER__FAILED: 'CREATE_USER_FAILED',

  EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
  EDIT_USER__FAILED: 'EDIT_USER_FAILED',

  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER__FAILED: 'DELETE_USER__FAILED',

  FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
  FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

  FETCH_TOP_DOCTORS_SUCCESS: 'FETCH_TOP_DOCTORS_SUCCESS',
  FETCH_TOP_DOCTORS_FAILED: 'FETCH_TOP_DOCTORS_FAILED',

  FETCH_ALL_DOCTORS_SUCCESS: 'FETCH_ALL_DOCTORS_SUCCESS',
  FETCH_ALL_DOCTORS_FAILED: 'FETCH_ALL_DOCTORS_FAILED',

  SAVE_DETAIL_DOCTORS_SUCCESS: 'SAVE_DETAIL_DOCTORS_SUCCESS',
  SAVE_DETAIL_DOCTORS_FAILED: 'SAVE_DETAIL_DOCTORS_FAILED',

  // schedule time allcode removed; components use time-slots API

  FETCH_REQUIRED_DOCTOR_Infor_START: 'FETCH_REQUIRED_DOCTOR_Infor_START',
  FETCH_REQUIRED_DOCTOR_Infor_SUCCESS: 'FETCH_REQUIRED_DOCTOR_Infor_SUCCESS',
  FETCH_REQUIRED_DOCTOR_Infor_FAILED: 'FETCH_REQUIRED_DOCTOR_Infor_FAILED',
});

export default actionTypes;
